FOLDER: './experiments' # Experiment files saving path

TEST:
  FOLDER: './results' # Testing files saving path

DATASET:
  SMPL_PATH: './deps/smpl'
  TRANSFORM_PATH: './deps/transforms/'
  WORD_VERTILIZER_PATH: './deps/glove/'
  KIT:
    ROOT: './datasets/kit-ml' # KIT directory
    SPLIT_ROOT: './datasets/kit-ml' # KIT splits directory
  HUMANML3D:
    # ROOT: '/work/vig/zhonglei/stylized_motion/dataset/mocap' # HumanML3D directory
    # SPLIT_ROOT: '/work/vig/zhonglei/stylized_motion/dataset/mocap' # HumanML3D splits directory
    # ROOT: '/work/vig/zhonglei/stylized_motion/dataset/100STYLE' # HumanML3D directory
    # SPLIT_ROOT: '/work/vig/zhonglei/stylized_motion/dataset/100STYLE' # HumanML3D splits directory

    ROOT: '/home/lei/dataset_all' # HumanML3D directory
    SPLIT_ROOT: '/home/lei/dataset_all'
    
    # ROOT: '/work/vig/zhonglei/stylized_motion/dataset/HumanML3D' # HumanML3D directory
    # SPLIT_ROOT: '/work/vig/zhonglei/stylized_motion/dataset/HumanML3D'
  HUMANACT12:
    ROOT: ./datasets/HumanAct12Poses
    SPLIT_ROOT: ./datasets/HumanAct12Poses
  UESTC:
    ROOT: ./datasets/uestc
    SPLIT_ROOT: ./datasets/uestc
  AMASS:
    DB_ROOT: /apdcephfs/share_1227775/shingxchen/uicap/data/vibe_db

model:
  bert_path: './deps/distilbert-base-uncased' # bert model path for all text encoders
  clip_path: './deps/clip-vit-large-patch14' # bert model path for all text encoders
  t2m_path: './deps/t2m/'

  humanact12_rec_path: './deps/actionrecognition'
  uestc_rec_path: './deps/actionrecognition'
  # Set model path separately for different encoders
  # TEXT_ENCODER:
  #   MODELPATH: './deps/distilbert-base-uncased' # bert model path for text encoder
  # TEXT_STYLE_ENCODER:
  #   MODELPATH: './deps/distilbert-base-uncased' # bert model path for text style encoder
  # TEXT_CONTENT_ENCODER:
  #   MODELPATH: './deps/distilbert-base-uncased' # bert model path for text content encoder

RENDER:
  BLENDER_PATH: '/work/vig/zhonglei/stylized_motion/blender-2.93.14-linux-x64/blender'
  FACES_PATH: '/work/vig/zhonglei/stylized_motion/motion-latent-diffusion/deps/smpl_models/smplh/smplh.faces'
  FOLDER: ./animations
